apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.81
    helm:
      releaseName: aws-load-balancer-controller
  destination:
    server: "https://kubernetes.default.svc"
    namespace: aws-load-balancer-controller
